package com.example.coen_elec_390_project;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

//TODO @Asha @Pavi it seems that this class has many methods that aren't used. Let me know if this isn't the case or please clean them up.
/**
 * This class represents each user and their biometrics
 * @author David Molina (4011257), Asha Islam (), Pavithra Sivagnanasunthrama()
 */
public class User {
    private String name;
    private String DoB;
    private String location;
    private int height;
    private double weight;
    private String userId;
    //this is the email address that we are going to be getting from the login
    private String email_address;

    /**
     * Default constructor
     */
    public User() {

    }

    /**
     * Custom constructor
     * @param name user's name
     * @param DoB user's date of birth
     * @param location user's location
     * @param height user's height
     * @param weight user's weight
     * @param email user's email
     */
    public User(String name, String DoB, String location, String height, String weight,String email) {
        this.name = name;
        this.DoB = DoB;
        this.location = location;
        this.height = Integer.parseInt(height);
        this.weight = Double.parseDouble(weight);
        this.email_address = email;
    }

    //not writing Javadoc for this one now, until you confirm that this method is used or not. Same for all other methods that seem unused.
    public void writeToFirebase() {
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        DatabaseReference usersRef = database.getReference("users");
        DatabaseReference userRef = usersRef.push();
        userRef.child("id").setValue(userRef.getKey()); // store the unique key generated by push() method
        userRef.child("name").setValue(name);
        userRef.child("dob").setValue(DoB);
        userRef.child("location").setValue(location);
        userRef.child("height").setValue(height);
        userRef.child("weight").setValue(weight);
        userRef.child("email").setValue(email_address);
    }
//this one too
    public void updateToFirebase() {
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        DatabaseReference usersRef = database.getReference().child("users");
        DatabaseReference userRef = usersRef.child(userId);

        // Update the fields only if they are not empty
        if (!name.isEmpty()) {
            userRef.child("name").setValue(name);
        }
        if (!DoB.isEmpty()) {
            userRef.child("dob").setValue(DoB);
        }
        if (!location.isEmpty()) {
            userRef.child("location").setValue(location);
        }
        if (height != 0) {
            userRef.child("height").setValue(height);
        }
        if (weight != 0.0) {
            userRef.child("weight").setValue(weight);
        }
    }


    /**
     * Gets user's name
     * @return user's name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets user's name
     */
    public void setName(String name) {
        this.name = name;
    }

    public String getDoB() {
        return DoB;
    }

    /**
     * Sets user's DOB
     */
    public void setDoB(String DoB) {
        this.DoB = DoB;
    }

    public String getLocation() {
        return location;
    }

    /**
     * Sets user's location
     * @param location user's location
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Gets user's height
     * @return user's height
     */
    public int getHeight() {
        return height;
    }

    /**
     * Sets user's height
     * @param height user's height
     */
    public void setHeight(int height) {
        this.height = height;
    }

    public double getWeight() {
        return weight;
    }

    /**
     * Sets user's weight
     * @param weight user's weight
     */
    public void setWeight(double weight) {
        this.weight = weight;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getEmailAddress() {
        return email_address;
    }

    public void setEmailAddress(String email_address) {
        this.email_address = email_address;
    }


}
